# Configuration for issue templates
blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/DevAyesh/weather-app/discussions
    about: Please ask and answer questions here.
