name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      
      # Backend setup
      - name: Setup Node.js for backend
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      
      - name: Install & Build backend
        working-directory: ./backend
        run: |
          npm ci
          npm run build --if-present
          
      # Frontend setup
      - name: Setup Node.js for frontend
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install & Build frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build --if-present
      
      # Environment setup (EXACTLY as you specified)
      - name: Setup environment variables
        run: |
          touch .env
          echo "${{ secrets.ENV }}" > .env